DELETE from settings WHERE settings_key LIKE 'dpinText.%'; ;
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.en', true, 'Your privacy and data security are very important to the New York State Department of Health. The COVID Alert NY app protects the privacy of all app users, at all times.\n\n**You remain anonymous to us and other app users. The app does not allow us or anyone else to:**\n- Collect your name, address, or any other personally identifiable information.\n- Track your location.\n- Access any information on your phone outside of this app.\n\n**It''s always your own personal choice to:**\n- Use the app or not.\n- Share your demographics and symptoms in the health log.\n\n[Read our comprehensive privacy policy](https://coronavirus.health.ny.gov/covidalert-privacy)');
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.ht', true, 'Sekirite enfòmasyon prive w ak done w yo enpòan anpil pou Depatman Sante Eta New York. Aplikasyon COVID Alert NY la pwoteje enfòmasyon prive tout moun k ap itilize aplikasyon an, tout tan.\n\n**Ou rete anonim pou nou ak pou lòt moun k ap itilize aplikasyon an. Aplikasyon an pa pèmèt nou menm ni nenpòt lòt moun pou:**\n- Rasanble non w, adrès ou oswa nenpòt lòt enfòmasyon pèsonèl idantifyab.\n- Lokalize kote w ye a.\n- Aksede nenpòt enfòmasyon sou telefòn ou andeyò aplikasyon sa a.\n\n**Se toujou pwòp chwa pèsonèl ou pou:**\n- Itilize aplikasyon an oswa pou w pa itilize l.\n- Pataje enfòmasyon demografik ou yo ak sentòm ou yo nan rejis sante a.\n\n[Li règleman konplè sou konfidansyalite vi prive nou an](https://coronavirus.health.ny.gov/covidalert-privacy)');
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.es', true, 'Su privacidad y la seguridad de sus datos son muy importantes para el Departamento de Salud del Estado de Nueva York. La aplicación COVID Alert NY protege la privacidad de todos sus usuarios, en todo momento.\n\n**Usted conserva su anonimato ante nosotros y otros usuarios. La aplicación no nos permite a nosotros ni a nadie:**\n- Recopilar su nombre, dirección ni cualquier otra información de identificación personal.\n- Rastrear su ubicación.\n- Acceder a cualquier información en su teléfono fuera de esta aplicación.\n\n**Siempre es su elección personal:**\n- Usar o no la aplicación.\n- Asentar sus datos demográficos y síntomas en el registro de salud.\n\n[Lea nuestra política de privacidad integral](https://coronavirus.health.ny.gov/covidalert-privacy)');
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.bn', true, 'নিউ ইয়র্ক স্টেট স্বাস্থ্য দপ্তরের কাছে আপনার গোপনীয়তা এবং ডেটা নিরাপত্তা অত্যন্ত গুরুত্বপূর্ণ। COVID Alert NY অ্যাপ সর্বদা সমস্ত অ্যাপ ব্যবহারকারীর গোপনীয়তা রক্ষা করে।\n\n**আপনি আমাদের এবং অন্যান্য ব্যবহারকারীর কাছে নামহীন থাকবেন। এই অ্যাপ আমাদের বা অন্য কোনো ব্যক্তিকে নিম্নোক্ত কাজের অনুমতি প্রদান করে না:**\n- আপনার নাম, ঠিকানা অথবা ব্যক্তিগতভাবে চিহ্নিতকরণযোগ্য যেকোনো তথ্য সংগ্রহ।\n- আপনার অবস্থান ট্র্যাক করুন।\n- এই অ্যাপের বাইরে আপনার ফোনে যেকোনো তথ্যে অ্যাকসেস।\n\n**নিম্নোক্ত কাজ সর্বদা আপনার একটি ব্যক্তিগত পছন্দের বিষয়:**\n- অ্যাপটি ব্যবহার করা বা না করা।\n- আপনার এলাকার জনসংখ্যার গঠন সংক্রান্ত তথ্য এবং হেলথ লগে আপনার উপসর্গগুলির ব্যবহার।\n\n[আমাদের পূর্ণাঙ্গ গোপনীয়তা নীতি পড়ুন](https://coronavirus.health.ny.gov/covidalert-privacy)');
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.ko', true, '귀하의 개인정보와 정보 보안은 뉴욕주 보건부(New York State Department of Health)에 중요한 사안입니다. COVID Alert NY 앱은 모든 앱 사용자의 개인정보를 항상 보호합니다.\n\n**여러분은 저희와 다른 앱 사용자에게 익명으로 남습니다. 이 앱은 저희 또는 다른 사람이 다음의 행위를 하지 ‘못하게’ 막습니다.**\n- 귀하의 이름, 주소 또는 다른 모든 개인 식별 정보의　수집.\n- 귀하의 위치 추적.\n- 이 앱 외부에 있는 전화기상의 모든 정보에　액세스.\n\n**다음의 선택은 항상 개인의 선택입니다:**\n- 앱의 사용 유무.\n- 건강 일지에서 귀하의 인구 통계학적 정보 및 증상 공유.\n\n[당국의 개인정보 취급방침 읽기](https://coronavirus.health.ny.gov/covidalert-privacy)');
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.ru', true, 'Ваши конфиденциальность и безопасность данных очень важны для Департамента здравоохранения штата Нью-Йорк (New York State Department of Health, NYSDOH). Приложение COVID Alert NY всегда защищает безопасность всех своих пользователей.\n\n**Ваша личность будет неизвестна нам и другим пользователям. Приложение не позволит нам или другим людям:**\n- Узнать ваши имя и фамилию, адрес или другие персональные данные, раскрывающие вашу личность.\n- Отслеживать ваше местоположение.\n- Получать доступ к информации на вашем телефоне вне этого приложения.\n\n**Вы всегда решаете сами:**\n- Пользоваться этим приложением или нет.\n- Записывать свои демографические данные и симптомы в журнал здоровья или нет.\n\n[Прочитать полную политику конфиденциальности](https://coronavirus.health.ny.gov/covidalert-privacy)');
INSERT INTO settings(settings_key, is_language, settings_value) VALUES('dpinText.zh', true, '维护您的隐私和数据安全对于纽约州卫生厅（New York State Department of Health, NYSDOH）而言至关重要。COVID Alert NY应用始终保护所有用户的隐私。\n\n**我们和其他应用用户都无法获取您的身份信息。使用应用时，我们或任何人都不可以：**\n- 收集您的姓名，地址或任何其他个人身份信息。\n- 追踪您的位置信息。\n- 获取您手机上此应用之外的其他信息。\n\n**您始终可以自由选择：**\n- 是否使用此应用。\n- 在健康日志中分享您的症状和人口统计信息。\n\n[阅读我们的全面隐私政策](https://coronavirus.health.ny.gov/covidalert-privacy)');


