ALTER TABLE verifications
ADD COLUMN IF NOT EXISTS long_code TEXT NULL;

CREATE TABLE IF NOT EXISTS enx_onboarding_requests (
  id UUID PRIMARY KEY NOT NULL DEFAULT GEN_RANDOM_UUID(),
  event_date DATE NOT NULL,
  all_counts INT NOT NULL DEFAULT 0,
  success_counts INT NOT NULL DEFAULT 0,
  settings_counts INT NOT NULL DEFAULT 0,
  enbuddy_counts INT NOT NULL DEFAULT 0,
  healthenbuddy_counts INT NOT NULL DEFAULT 0
);

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO read_write;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO read_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO read_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO read_write;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_only;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO read_only;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO read_only;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO read_only;