ALTER TABLE verifications
ADD COLUMN IF NOT EXISTS mobile TEXT NULL,
ADD COLUMN IF NOT EXISTS last_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
ADD COLUMN IF NOT EXISTS send_count INT NOT NULL DEFAULT 1;